name: masterworkflows 

on: 
  push:

jobs: 
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          pwd
          ls -ltr
          hostname
      - name: checkout 
        uses: actions/checkout@v5.0.0
      - name: step3
        run: |
          pwd
          ls -ltr
          hostname
          
      