name: workflows 

on: push

jobs: 
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: running single command in Job1
        run: echo "Hi this is my first Githubworkflow"
      - name: Checkign OS release for GitHub Hosted runner"
        run: cat /etc/os-release
      - name: calling sleep
        run: sleep 20
  
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: checking the host name for runner
        run: hostname
      - name: Running multiple commands
        run: |
          echo "Hi from kumar"
          echo "Current time is `date`"
  job3: 
    name: JOB3
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - name: Jobs with single dependency
        run: sleep 20
  
  job4: 
    name: JOB4 
    runs-on: ubuntu-latest
    needs: [job1,job2,job3]
    steps: 
      - name: Jobs with multiple dependecny
        run: sleep 10


   

