name: workflows 

on: push

jobs: 
   job1:
     name: JOB1
     runs-on: ubuntu-latest
     steps:
        - name: running single command in Job1
          run: echo "Hi this is my first Githubworkflow"
        - name: Checkign OS release for GitHub Hosted runner"
          run: cat /etc/os-release


   

